// This file have been generated by SRGEnt-Generator
//using SRGEnt;
using SRGEnt.Aspects;
using SRGEnt.Interfaces;

namespace SRGEnt.Generated
{
    public class SingleComponentTestMatcher : AspectMatcher, IAspectMatcher<SingleComponentTestAspectSetter>
    {
        private static readonly Aspect _empty = new Aspect(SingleComponentTestEntity.AspectSize);
        public SingleComponentTestMatcher() : base(SingleComponentTestEntity.AspectSize)
        {
        }

        public SingleComponentTestAspectSetter Requires => new SingleComponentTestAspectSetter(this, Required);
        public SingleComponentTestAspectSetter CannotHave => new SingleComponentTestAspectSetter(this, Forbidden);
        public SingleComponentTestAspectSetter ShouldHaveAtLeastOneOf => new SingleComponentTestAspectSetter(this, AnyOf);
        public void RecalculateHash()
        {
            base.RecalculateHashCode();
        }

        protected override ref readonly Aspect Empty => ref _empty;
    }
}