// This file have been generated by SRGEnt-Generator
namespace SRGEnt.Generated
{
    public interface IFirstComponent<T>
    {
        T FirstComponent { get; set; }

        bool HasFirstComponent { get; }

        void RemoveFirstComponent();
    }
}