// This file have been generated by SRGEnt-Generator
using SRGEnt.Aspects;
using SRGEnt.Interfaces;

namespace SRGEnt.Generated
{
    public readonly struct SingleComponentTestAspectSetter : IAspectMatcher<SingleComponentTestAspectSetter>, IFirstComponentAspect<SingleComponentTestAspectSetter>
    {
        private readonly SingleComponentTestMatcher _parent;
        private readonly Aspect _aspect;
        public SingleComponentTestAspectSetter(SingleComponentTestMatcher parent, Aspect aspect)
        {
            _parent = parent;
            _aspect = aspect;
        }

        public SingleComponentTestAspectSetter Requires => _parent.Requires;
        public SingleComponentTestAspectSetter CannotHave => _parent.CannotHave;
        public SingleComponentTestAspectSetter ShouldHaveAtLeastOneOf => _parent.ShouldHaveAtLeastOneOf;
        public void RecalculateHash()
        {
            _parent.RecalculateHash();
        }

        public SingleComponentTestAspectSetter FirstComponent()
        {
            _aspect.Set(new AspectIndex(SingleComponentTestEntity.FIRSTCOMPONENT_INDEX));
            return this;
        }
    }
}