// This file have been generated by SRGEnt-Generator
using SRGEnt.Systems;

namespace SRGEnt.Generated
{
    public abstract class TestExecuteSystem : ExecuteSystem<TestEntity, TestDomain, TestMatcher, TestAspectSetter>
    {
        protected TestExecuteSystem(TestDomain domain, bool shouldSort = false) : base(domain, shouldSort)
        {
        }
    }
}