// This file have been generated by SRGEnt-Generator
using SRGEnt.Systems;

namespace SRGEnt.Generated
{
    public abstract class TestDomainExecuteSystem : ExecuteSystem<TestEntity, TestDomain, TestMatcher, TestAspectSetter>
    {
        protected TestDomainExecuteSystem(TestDomain domain, bool shouldSort = false) : base(domain, shouldSort)
        {
        }
    }
}