// This file have been generated by SRGEnt-Generator
using SRGEnt.Systems;

namespace SRGEnt.Generated
{
    public abstract class TestReactiveSystem : ReactiveSystem<TestEntity, TestDomain, TestMatcher, TestAspectSetter>
    {
        protected TestReactiveSystem(TestDomain domain, bool shouldSort = false) : base(domain, shouldSort)
        {
        }
    }
}