// This file have been generated by SRGEnt-Generator
using SRGEnt.Aspects;
using SRGEnt.Interfaces;

namespace SRGEnt.Generated
{
    public readonly struct TestAspectSetter : IAspectMatcher<TestAspectSetter>
    {
        private readonly TestMatcher _parent;
        private readonly Aspect _aspect;
        public TestAspectSetter(TestMatcher parent, Aspect aspect)
        {
            _parent = parent;
            _aspect = aspect;
        }

        public TestAspectSetter Requires => _parent.Requires;
        public TestAspectSetter CannotHave => _parent.CannotHave;
        public TestAspectSetter ShouldHaveAtLeastOneOf => _parent.ShouldHaveAtLeastOneOf;
        public void RecalculateHash()
        {
            _parent.RecalculateHash();
        }
    }
}