// This file have been generated by SRGEnt-Generator
//using SRGEnt;
using SRGEnt.Aspects;
using SRGEnt.Interfaces;

namespace SRGEnt.Generated
{
    public class TestMatcher : AspectMatcher, IAspectMatcher<TestAspectSetter>
    {
        private static readonly Aspect _empty = new Aspect(TestEntity.AspectSize);
        public TestMatcher() : base(TestEntity.AspectSize)
        {
        }

        public TestAspectSetter Requires => new TestAspectSetter(this, Required);
        public TestAspectSetter CannotHave => new TestAspectSetter(this, Forbidden);
        public TestAspectSetter ShouldHaveAtLeastOneOf => new TestAspectSetter(this, AnyOf);
        public void RecalculateHash()
        {
            base.RecalculateHashCode();
        }

        protected override ref readonly Aspect Empty => ref _empty;
    }
}