// This file have been generated by SRGEnt-Generator

namespace SRGEnt.Generated
{
    public interface ISecondComponentPrimaryIndex<TEntity, TComponentType>
        where TEntity : struct, ISecondComponent<TComponentType>
    {
        TEntity? GetEntityWithSecondComponent(TComponentType value);
    }
}