// This file have been generated by SRGEnt-Generator

namespace SRGEnt.Generated
{
    public interface IFirstComponentPrimaryIndex<TEntity, TComponentType>
        where TEntity : struct, IFirstComponent<TComponentType>
    {
        TEntity? GetEntityWithFirstComponent(TComponentType value);
    }
}