// This file have been generated by SRGEnt-Generator
namespace SRGEnt.Generated
{
    public interface ISecondComponent<T>
    {
        T SecondComponent { get; set; }

        bool HasSecondComponent { get; }

        void RemoveSecondComponent();
    }
}