// This file have been generated by SRGEnt-Generator
using SRGEnt;
using SRGEnt.Aspects;
using SRGEnt.Interfaces;

namespace SRGEnt.Generated
{
    public class PrimaryIndexComponentTestMatcher : AspectMatcher, IAspectMatcher<PrimaryIndexComponentTestAspectSetter>
    {
        private static readonly Aspect _empty = new Aspect(PrimaryIndexComponentTestEntity.AspectSize);
        public PrimaryIndexComponentTestMatcher() : base(PrimaryIndexComponentTestEntity.AspectSize)
        {
        }

        public PrimaryIndexComponentTestAspectSetter Requires => new PrimaryIndexComponentTestAspectSetter(this, Required);
        public PrimaryIndexComponentTestAspectSetter CannotHave => new PrimaryIndexComponentTestAspectSetter(this, Forbidden);
        public PrimaryIndexComponentTestAspectSetter ShouldHaveAtLeastOneOf => new PrimaryIndexComponentTestAspectSetter(this, AnyOf);
        public void RecalculateHash()
        {
            base.RecalculateHashCode();
        }

        protected override ref readonly Aspect Empty => ref _empty;
    }
}