// This file have been generated by SRGEnt-Generator
using SRGEnt.Systems;

namespace SRGEnt.Generated
{
    public abstract class SingleComponentTestDomainReactiveSystem : ReactiveSystem<SingleComponentTestEntity, SingleComponentTestDomain, SingleComponentTestMatcher, SingleComponentTestAspectSetter>
    {
        protected SingleComponentTestDomainReactiveSystem(SingleComponentTestDomain domain, bool shouldSort = false) : base(domain, shouldSort)
        {
        }
    }
}