// This file have been generated by SRGEnt-Generator
using SRGEnt.Systems;

namespace SRGEnt.Generated
{
    public abstract class SingleComponentTestDomainExecuteSystem : ExecuteSystem<SingleComponentTestEntity, SingleComponentTestDomain, SingleComponentTestMatcher, SingleComponentTestAspectSetter>
    {
        protected SingleComponentTestDomainExecuteSystem(SingleComponentTestDomain domain, bool shouldSort = false) : base(domain, shouldSort)
        {
        }
    }
}